version: '3'

services:
    mysql:
        image: mysql:latest
        container_name: app_mysql
        ports:
            - "${MYSQL_HOST_PORT}:3306"
        volumes:
            - ./runtime/mysql/data:/var/lib/mysql
            - ./runtime/mysql/log:/var/log/mysql
            - ./runtime/mysql/mysql-files:/var/lib/mysql-files
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        security_opt:
            - seccomp:unconfined

    node:
        build: ./docker/node
        working_dir: /usr/src/app
        container_name: app_node
        environment:
            NODE_ENV: ${NODE_ENV}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            PORT: 3000
        volumes:
            - .:/usr/src/app
        ports:
            - "${NODE_HOST_PORT}:3000"
        command: bash -c "npm -i; npm -i --dev; npm run init-app; while [ true ]; do sleep 600; done"
